"""Loading (and validating) the bundled reference data.

Everything in ``fos_cazavi/data`` is generated by :mod:`fos_cazavi.build_data`
from an AMRFinderPlus release.  This module
reads it back in and re-checks the one property that silently ruins results if
it is wrong: that every mutation position really does carry the reference
residue the table claims, in the reference protein it is numbered against.
"""

import csv
import sys
from collections import defaultdict
from pathlib import Path

from Bio import SeqIO

DATA_DIR = Path(__file__).parent / 'data'
REFERENCE_PROTEINS = DATA_DIR / 'reference_proteins.faa'
POINT_MUTATIONS = DATA_DIR / 'point_mutations.tsv'
DEFAULT_DATABASE = DATA_DIR / 'example_database.fasta'

# Gene-name prefixes for horizontally acquired resistance genes.  Presence of
# the gene is itself the finding; differences from the reference allele are
# real variant calls rather than species variation.
ACQUIRED_PREFIXES = ('bla', 'fosA', 'fosB', 'fosC', 'fosL')

# Organisms for which point mutations are curated.  These are AMRFinderPlus
# taxgroup names, used verbatim so the two data sets line up.
SUPPORTED_ORGANISMS = (
    'Escherichia',
    'Klebsiella_pneumoniae',
    'Pseudomonas_aeruginosa',
)

# Metallo-beta-lactamases: avibactam does not inhibit them, so their presence
# is sufficient for ceftazidime-avibactam resistance regardless of any KPC.
MBL_FAMILIES = ('blaNDM', 'blaVIM', 'blaIMP', 'blaSPM', 'blaGIM', 'blaSIM')

# Chromosomal genes where a curated mutation can *contribute* to
# ceftazidime-avibactam resistance without being sufficient on its own: the
# porin OmpK36, the PBP3 transpeptidase FtsI, and the EnvZ sensor kinase that
# regulates porin expression.  These raise MICs in combination with a
# beta-lactamase rather than conferring resistance by themselves, so they are
# scored as uncertain evidence, never as a Resistant call.
CAZAVI_CONTRIBUTORY_GENES = ('envZ', 'ftsI', 'ompK36', 'ompC', 'ompF')

# Porins whose loss of function amplifies a beta-lactamase: OmpK36 in
# K. pneumoniae, OmpC/OmpF in E. coli.  OmpK35 is
# deliberately excluded: its truncation is near-universal background in clinical
# K. pneumoniae, so scoring it would make Indeterminate the default for most
# isolates without discriminating anything.  OmpK36 is the porin the
# ceftazidime-avibactam literature implicates.
PORIN_GENES = ('ompK36', 'ompC', 'ompF')

# Beta-lactamases whose activity reduced drug entry can amplify enough to raise
# ceftazidime-avibactam MICs.  Avibactam inhibits all of these, so none of them
# alone is resistance - but combined with porin loss they are a documented route
# to a resistant phenotype without any carbapenemase.
PERMEABILITY_AMPLIFIED_FAMILIES = ('blaKPC', 'blaCMY', 'blaCTX-M', 'blaSHV', 'blaPDC')

# Enzymes that inactivate fosfomycin.
FOSA_FAMILIES = ('fosA', 'fosB', 'fosC', 'fosL')

# The chromosomal fosfomycin transport / regulatory genes.  Loss of function in
# any of these reduces fosfomycin uptake; the mechanism does not depend on
# which residue was hit, so it is detected as loss of function rather than from
# a position list.
FOS_TRANSPORT_GENES = ('uhpT', 'uhpA', 'uhpB', 'uhpC', 'glpT', 'cyaA', 'ptsI', 'galU')

# Chromosomal fosA enzymes that are a normal part of a species' genome: the
# K. pneumoniae one (carried here both as fosAKP and as its AMRFinderPlus name
# fosA6) and the P. aeruginosa one.  They are present in fosfomycin-susceptible
# isolates, so they are reported but never scored as acquired resistance.
INTRINSIC_GENES = ('fosAKP', 'fosA6', 'fosA_PA1129')

# Genera whose chromosome normally carries a fosA-family enzyme.  In these, a
# lone fosA hit with no recognised intrinsic copy is ambiguous: it may be a
# divergent chromosomal enzyme rather than an acquired one.
INTRINSIC_FOSA_ORGANISMS = ('Klebsiella_pneumoniae', 'Pseudomonas_aeruginosa')

# Species that are intrinsically resistant to fosfomycin, so that a "no acquired
# mechanism found" result must not be reported as susceptible.  P. aeruginosa
# carries the chromosomal FosA (PA1129) and has no fosfomycin breakpoints in the
# EUCAST/CLSI tables; fosfomycin is not an agent for it.
INTRINSIC_FOS_RESISTANT_ORGANISMS = ('Pseudomonas_aeruginosa',)

# Species whose dominant ceftazidime-avibactam resistance mechanism this tool
# does not assess.  In P. aeruginosa that is the chromosomal AmpC (PDC/blaPAO):
# derepression and PDC variants drive most CAZ/AVI resistance, and neither the
# expression level nor the PDC variant catalogue is covered here, so a negative
# result cannot be reported as susceptible.
UNASSESSED_CAZAVI_MECHANISM = {
    'Pseudomonas_aeruginosa': (
        'chromosomal AmpC (PDC/blaPAO) derepression and PDC variants, which '
        'drive most ceftazidime-avibactam resistance in this species, are not '
        'assessed by this tool'
    ),
}

# This tool reports on two drugs.  A curated mutation carries the scope it was
# curated for, so a tigecycline or carbapenem mutation is never presented as a
# fosfomycin or ceftazidime-avibactam finding.
FOS_SCOPE = 'fosfomycin'
CAZAVI_SCOPE = 'ceftazidime-avibactam'
AVIBACTAM_COMBINATION_SCOPE = 'avibactam-combination'
IN_SCOPE_DRUGS = (FOS_SCOPE, CAZAVI_SCOPE, AVIBACTAM_COMBINATION_SCOPE)


def mutation_scope(row):
    """The drug scope a curated mutation row belongs to.

    Falls back to classifying the Class/Subclass text directly, so a
    user-supplied mutation table without a Drug_Scope column still works.
    """
    scope = (row.get('Drug_Scope') or '').strip()
    if scope:
        return scope
    combined = f"{row.get('Class', '')}/{row.get('Subclass', '')}".upper()
    if 'FOSFOMYCIN' in combined:
        return FOS_SCOPE
    if 'CEFTAZIDIME-AVIBACTAM' in combined:
        return CAZAVI_SCOPE
    if 'AVIBACTAM' in combined:
        return AVIBACTAM_COMBINATION_SCOPE
    return 'other'


def gene_family(gene_name):
    """Base family of a reference gene name, e.g. blaKPC-2 -> blaKPC."""
    base = gene_name.split('|')[0]
    if '-' in base and base.startswith('bla'):
        # blaCTX-M-15 -> blaCTX-M ; blaKPC-2 -> blaKPC
        parts = base.split('-')
        while parts and parts[-1].isdigit():
            parts.pop()
        return '-'.join(parts) if parts else base
    if base.startswith('fosA') and base[4:].isdigit():
        return 'fosA'
    return base


def is_acquired_gene(gene_name):
    if gene_name in INTRINSIC_GENES:
        return False
    return gene_name.startswith(ACQUIRED_PREFIXES)


def is_mbl(gene_name):
    return gene_family(gene_name) in MBL_FAMILIES


def load_reference_proteins(path=REFERENCE_PROTEINS):
    """{(gene, organism): (accession, protein_sequence)}"""
    proteins = {}
    if not Path(path).exists():
        return proteins
    for record in SeqIO.parse(path, 'fasta'):
        parts = record.id.split('|')
        if len(parts) != 3:
            continue
        gene, organism, accession = parts
        proteins[(gene, organism)] = (accession, str(record.seq))
    return proteins


def _mutation_key(row, position):
    """Key a curated mutation the same way a called change is keyed.

    AMRFinderPlus writes an insertion as the residue plus what replaces it -
    ``ompK36_D135DGD`` means D135 becomes D-G-D, i.e. GD inserted after 135.
    The variant caller emits that as ``insGD@135``, so the stored key is
    normalised to the same shape here.
    """
    variant = row['Variant']
    if row.get('Kind') == 'insertion' and variant.startswith(row['Ref']):
        return (position, 'ins' + variant[len(row['Ref']):])
    return (position, variant)


def mutation_lookup_key(change):
    """Key a called change for lookup against the curated mutation table."""
    if change['kind'] == 'deletion':
        return (change['position'], 'del')
    if change['kind'] == 'insertion':
        return (change['position'], 'ins' + change['alt'])
    return (change['position'], change['alt'])


def load_point_mutations(path=None, reference_proteins=None):
    """Curated point mutations, keyed by (gene, organism) -> {(position, variant): row}.

    Rows whose reference residue does not match the reference protein are
    dropped with a warning: a mutation table that disagrees with its own
    reference cannot produce trustworthy calls.
    """
    path = Path(path) if path else POINT_MUTATIONS
    if not path.exists():
        return {}

    if reference_proteins is None:
        reference_proteins = load_reference_proteins()

    mutations = defaultdict(dict)
    dropped = 0

    with open(path) as handle:
        for row in csv.DictReader(handle, delimiter='\t'):
            try:
                position = int(row['Position'])
            except (KeyError, ValueError):
                continue
            gene, organism = row['Gene'], row.get('Organism', '')
            reference = reference_proteins.get((gene, organism))

            if reference is not None:
                _, sequence = reference
                if position > len(sequence) or sequence[position - 1] != row['Ref']:
                    print(f"WARNING: dropping {row.get('Label', gene)}: reference residue "
                          f"{row['Ref']}{position} does not match the reference protein",
                          file=sys.stderr)
                    dropped += 1
                    continue

            mutations[(gene, organism)][_mutation_key(row, position)] = row

    if dropped:
        print(f"WARNING: {dropped} mutation definition(s) dropped as inconsistent "
              f"with their reference protein", file=sys.stderr)
    return dict(mutations)


def data_version():
    version_file = DATA_DIR / 'DATA_VERSION.txt'
    if version_file.exists():
        return version_file.read_text().strip()
    return 'unknown'
